services:
  rocket-server:
    build: .
    restart: always
    environment:
      VIRTUAL_HOST:     fs.mader.xyz, fs.mader.lo
      LETSENCRYPT_HOST: fs.mader.xyz       
      LETSENCRYPT_MAIL: vincent.mader@icloud.com
    ports:
      - 8004:8000  
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
    name: proxy_mxyz_proxy_network 
    # ^ This has to be the same name as specified in the `docker-compose.yml` file 
    #   of your reverse-proxy server. Additionally, it has to be prefixed by the proxy 
    #   directory name (see "docker network ls").
    #
    #   If you have not set up a reverse-proxy server yet, take a look at:
    #   -> https://github.com/vincentmader/docker-reverse-proxy
